#!/bin/bash
TEMP_FOLDER="/aerospike-tmp"
CONFIG_FOLDER="/aerospike-tmp"

echo "Setting-up ..."
rm -r $TEMP_FOLDER
mkdir $TEMP_FOLDER
clear

echo "Install Aerospike ..."
cd $TEMP_FOLDER
sudo apt-get -y update
sudo wget -O aerospike-server.tgz http://www.aerospike.com/download/server/latest/artifact/debian7
sudo tar -zxvf aerospike-server.tgz
cd aerospike-server-community-*
sudo ./asinstall
clear

echo "Install Aerospike Management Console (AMC) ..."
sudo wget -O aerospike-management-console.deb http://www.aerospike.com/download/amc/latest/artifact/debian6
sudo dpkg -i aerospike-management-console.deb
sudo apt-get -y -f install
clear

echo "Install Config File"
sudo rm -r $CONFIG_FOLDER/*
sudo cp $TEMP_FOLDER/cluster_config/* $CONFIG_FOLDER

echo "Starting Services ..."
sudo service aerospike start
sudo service amc start
